export const roleBoundaries = {
  planner: {
    maxTurns: 30,
    owned: [],
    forbidden: ['**'],
  },
  architect: {
    maxTurns: 30,
    owned: [],
    forbidden: ['**'],
  },
  engineer: {
    maxTurns: 40,
    owned: [
      '.gitignore',
      'README.md',
      'package.json',
      'package-lock.json',
      'pnpm-lock.yaml',
      'yarn.lock',
      'bun.lockb',
      'tsconfig*.json',
      '*.config.*',
      'functions/_middleware.js',
      'functions/api/_middleware.js',
      'functions/**',
      'workers/**',
      'src/**',
      'test/**',
      'lib/**',
      'scripts/**',
      'db/**',
      'migrations/**',
      'wrangler.jsonc',
      'wrangler.toml',
      '**/*.sql',
    ],
    forbidden: ['public/**', 'tests/**', 'server/**', 'api/**', 'app/**', 'prisma/**', '**/*.jsx', '**/*.tsx', 'next.config.*'],
  },
  designer: {
    maxTurns: 40,
    owned: [
      'public/**',
      'assets/**',
      'styles/**',
      'src/**/*.html',
      'src/**/*.css',
      'src/**/*.js',
      'src/**/*.mjs',
      'src/assets/**',
    ],
    forbidden: [
      'functions/**',
      'workers/**',
      'server/**',
      'api/**',
      'src/api/**',
      'src/server/**',
      'src/lib/server/**',
      'db/**',
      'prisma/**',
      'tests/**',
      'wrangler.jsonc',
      'wrangler.toml',
      '**/*.sql',
      '**/*.jsx',
      '**/*.tsx',
      'next.config.*',
    ],
  },
  tester: {
    maxTurns: 40,
    owned: ['tests/**', 'test/**', 'e2e/**', 'playwright.config.*', 'vitest.config.*'],
    forbidden: ['functions/**', 'workers/**', 'public/**', 'src/**', 'app/**', 'server/**', 'api/**'],
  },
  deployer: {
    maxTurns: 20,
    owned: [],
    forbidden: ['**'],
  },
  judge: {
    maxTurns: 20,
    owned: [],
    forbidden: ['**'],
  },
} as const;

export type DeliveryRole = keyof typeof roleBoundaries;

export const deliveryRoles = Object.keys(roleBoundaries) as DeliveryRole[];
